### ISSUE TITLE
How to choose the parameters?

### ISSUE THREAD

**Issue by jun1015** [ishtiyaque/FastPIR#1]
Hello！I found that the BFV parameters is set at bfvparams.h instead of using the default parameters in SEAL. How to determine the best paramters? For example if I'd like to use 8192 as the POLY_MODULUS_DEGREE how do I choose other parameters?

**Comment by ishtiyaque** [comment]
Hi, thanks for the great question. First of all, the easiest way to use FastPIR for a different  POLY_MODULUS_DEGREE is to use SEAL's default parameters and update the fastpirparams.cpp file accordingly. Otherwise, the best parameters depend on the performance metric you are optimizing for. If you want to reduce the answer generation time, having fewer primes for the ciphertext coefficient helps. But if the total size in bits of all the ciphertext coefficient primes is too small, then it might require compromising the size of PLAIN_MODULUS. So, there is a trade-off, and it might require some empirical analysis to find a sweet point that allows a large enough PLAIN_MODULUS and a smaller number of ciphertext coefficient primes. The performance does not depend on the size of each coefficient prime, so you may consider each prime to be as large as 60 bits until the aggregated size does not exceed the limit (e.g., 218 bits for POLY_MODULUS_DEGREE=8192, assuming 128-bit security). To determine the PLAIN_MODULUS for a particular bit-length, it helps to pick the smallest prime of that bit-length that satisfies the condition: PLAIN_MODULUS % (2 * POLY_MODULUS_DEGREE) = 1.
Please feel free to follow up if the clarification does not fully answer your question. Thanks.

**Comment by jun1015** [comment]
So the target is fewer primes for the ciphertext coefficient and larger PLAIN_MODULUS? Could you please explain the reason of fewer primes could reduce the response time?

**Comment by ishtiyaque** [comment]
Because any homomorphic operation on a ciphertext iterates over the components of its coefficients. The number of components is one less than the number of ciphertext coefficient primes, so more primes require more computation.

**Comment by jun1015** [comment]
Thanks! I got it!
